# Collaborative Filtering

准备数据集，使用 MovieLens 推荐的应用与开发和学习的 Small [数据集](http://files.grouplens.org/datasets/movielens/ml-latest-small.zip)。该数据集包含 600 位用户在 9000 个电影上的 100,000 个标签和 3600 个 Tag，这次不使用　Tag 只用打分数据。

In [2]:
import os

# working directory
BASEDIR = os.getcwd()
print(BASEDIR)

/home/hailingu/Git/MLFM


读取 MovieLens 数据集，并且构造出 rating 矩阵。矩阵的行对应于用户，矩阵的列对应于电影。

In [3]:
import pandas as pd
import numpy as np


dataframe = pd.read_csv(BASEDIR + '/assets/datasets/ml-latest-small/ratings.csv')

userId_dict = {}
movieId_dict = {}

userId_unique = dataframe.userId.unique()
movieId_unique = dataframe.movieId.unique()


idx = 0
for n in range(userId_unique.shape[0]):
    userId_dict[userId_unique[idx]] = idx
    idx += 1

idx = 0
for n in range(movieId_unique.shape[0]):
    movieId_dict[movieId_unique[idx]] = idx
    idx += 1

ratings = np.zeros(shape=(len(userId_dict), len(movieId_dict)))


for row in dataframe.itertuples():
    ratings[userId_dict[row.userId], movieId_dict[row.movieId]] = row.rating

## UserCF 

根据用户对 movie 的打分，对任意一个用户 u，找出与其相似度最高的 N 个用户（这里就采用 Top 10），计算用户 u 对未看过电影 m 的分，计算方法为： $Rate(u, m)=\frac{\sum_{s \in S} w_{u, s} Rate_{s, m}}{\sum w_{u,s}}$

所以先要计算 user 和 user 之间的相似度矩阵。

In [4]:
# first construct user-user collaborative matrix

user_user_cm = np.zeros(shape=(len(userId_dict), len(userId_dict)))

# set diagonal value to 1.0
for i in range(len(userId_dict)):
    user_user_cm[i, i] = 1.0


for i in range(len(userId_dict)):
    for j in range(i, len(userId_dict)):
        v_i = ratings[i, :]
        v_j = ratings[j, :]

        similarity = np.dot(v_i, v_j) / (np.linalg.norm(v_i) * np.linalg.norm(v_j))

        user_user_cm[i, j] = similarity
        user_user_cm[j, i] = similarity

在 user-user 相似度矩阵的基础之上，对于每一个 user， 找出与其相似的 Top N 个用户，然后通过这 N 个用户，填充 user 的对矩阵评分向量的缺失值。

In [5]:
# create a new rating matrix
usercf_ratings = np.zeros(shape=(len(userId_dict), len(movieId_dict)))

In [6]:
# for user 1, fill its rating vector
N = 10

top_n_idx = user_user_cm[1, :].argsort()[::-1][1:N + 1]
sum_weights = 0.0

for i in top_n_idx:
    sum_weights += user_user_cm[1, i]

for movieIdx in range(len(movieId_unique)):
    if ratings[1, movieIdx] is 0.0:
        for i in top_n_idx:
            usercf_ratings[1, movieIdx] += user_user_cm[1, i] * ratings[i, movieIdx]
        usercf_ratings[1, movieIdx] /= sum_weights
    else:
        usercf_ratings[1, movieIdx] = ratings[0, movieIdx]


print(ratings[1, 0:10])
print(usercf_ratings[1, 0:10])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4. 4. 4. 5. 5. 3. 5. 4. 5. 5.]


填充整个用户打分矩阵

In [7]:
N = 5
for i in range(len(userId_dict)):
    top_n_idx = user_user_cm[i, :].argsort()[::-1][1:N + 1]
    sum_weights = 0.0

    for j in top_n_idx:
        sum_weights += user_user_cm[i, j]

    for movieIdx in range(len(movieId_unique)):
        if ratings[i, movieIdx] is 0.0:
            for j in top_n_idx:
                usercf_ratings[i, movieIdx] += user_user_cm[i, j] * ratings[j, movieIdx]
            usercf_ratings[i, movieIdx] /= sum_weights
        else:
            usercf_ratings[i, movieIdx] = ratings[i, movieIdx]

在实际中，UserCF 会遇到两个问题：

- 原始 rating 矩阵稀疏的话，相似矩阵的计算会有很大的偏差
- 随着用户量的增长，需要 $O(N^2)$ 的存储和计算空间，这种规模是无法接受的

# ItemCF

根据观看过 movie 的 user，计算 movie 之间的相似度，得到 movie-movie 的相似度矩阵。然后根据 user 对 movie 的打分，找出相似度最高的 Top N 个 movie 给用户推荐。movie　和　movie　之间的相似度计算和　user 之间的不太一样：$w_{ij}=\frac{N(i) \cap N(j)}{\sqrt{|N(i)||N(j)|}}$，

先计算 movie 和 movie 之间的相似度矩阵。

In [8]:
# first construct movie-movie collaborative matrix

movie_movie_cm = np.zeros(shape=(len(movieId_dict), len(movieId_dict)))

# set diagonal value to 1.0
for i in range(len(movieId_dict)):
    movie_movie_cm[i, i] = 1.0


for i in range(len(movieId_dict)):
    for j in range(i, len(movieId_dict)):
        v_i = ratings[:, i]
        v_j = ratings[:, j]

        v_i[v_i > 0.0] = 1.0
        v_j[v_j > 0.0] = 1.0

        similarity = (1. / log(1 + np.dot(v_i, v_j))) / np.sqrt(np.linalg.norm(v_i, ord=1) * np.linalg.norm(v_j, ord=1))

        movie_movie_cm[i, j] = similarity
        movie_movie_cm[j, i] = similarity

In [9]:
# create a new rating matrix
itemcf_ratings = np.zeros(shape=(len(userId_dict), len(movieId_dict)))

In [11]:
# for user 1, find recommended movies
N = 10

user = ratings[1, :]
user_positive_movie = np.argwhere(user > 0)
for i in user_positive_movie:
    for j in range(len(movieId_dict)):
        itemcf_ratings[1, j] += ratings[1, i] * movie_movie_cm[i, j]
    for q in user_positive_movie:
        itemcf_ratings[1, q] = 0 

top_n_idx = itemcf_ratings[1, :].argsort()[::-1][1:N + 1]
print(top_n_idx)

[1054  926  809  192  927 1047  915 1317 1250 1051]


试着填充整个打分矩阵

In [ ]:
for u in range(len(userId_unique)):
    user = ratings[u, :]
    user_positive_movie = np.argwhere(user > 0)
    for i in user_positive_movie:
        for j in range(len(movieId_dict)):
            itemcf_ratings[1, j] += ratings[1, i] * movie_movie_cm[i, j]
        for q in user_positive_movie:
            itemcf_ratings[1, q] = 0

itemcf 的特点

- 推荐很稳定，这是优点也是缺点。因为总是会推荐一模一样的东西。
- 计算和存储空间虽然也是 $O(N^2)$，但是因为　item 增长的比较慢，所以会比　usercf　好很多。
- 依然无法处理稀疏性的问题

就　usercf　和　itemcf 来说都已经算是上古的推荐算法了。在实际中已经很少被使用了。